### ISSUE TITLE
formatErrorDescription may panic on concurrent invocations

### ISSUE THREAD

**Issue by johandorland** [xeipuuv/gojsonschema#129]
Since 32187ac8e8496dbb2a9e6df5191375cc401c8ffa formatErrorDescription uses the ```text/template``` package to format. According to the [documentation](https://godoc.org/text/template): ```Once parsed, a template may be executed safely in parallel.```

However when a template does not yet exists there is a race condition where creating a new template and lookups happen at the same time from different threads (for example when a schema is reused for validation multiple documents as mentioned in https://github.com/xeipuuv/gojsonschema/issues/77)

A possible solution is to introduce some locking around the errorTemplates variable in https://github.com/xeipuuv/gojsonschema/commit/e18f0065e8c148fcf567ac43a3f8f5b66ac0720b#diff-dd25e0e0a594c3f3592c1c717039b85eR244. Currently the initialization also doesn't seem to be thread-safe.

Ofcourse the chance of this happening is fairly small and it's a bit tough to reproduce, but I managed to get two stacktraces:

```
fatal error: concurrent map writes

goroutine 21 [running]:
runtime.throw(0x8d6000, 0x15)
	/usr/lib/golang/src/runtime/panic.go:547 +0x90 fp=0xc42004b4a0 sp=0xc42004b488
runtime.mapassign1(0x74c280, 0xc420017dd0, 0xc4200125c0, 0xc42004b570)
	/usr/lib/golang/src/runtime/hashmap.go:445 +0xb1 fp=0xc42004b548 sp=0xc42004b4a0
text/template.(*Template).associate(0xc4200125c0, 0xc4200125c0, 0xc42024c000, 0x19, 0x0, 0x0)
	/usr/lib/golang/src/text/template/template.go:216 +0x16f fp=0xc42004b5a0 sp=0xc42004b548
text/template.(*Template).AddParseTree(0xc4200125c0, 0x8efd40, 0x19, 0xc42024c000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/text/template/template.go:128 +0x220 fp=0xc42004b640 sp=0xc42004b5a0
text/template.(*Template).Parse(0xc4200125c0, 0x8efd40, 0x19, 0x19, 0x0, 0x0)
	/usr/lib/golang/src/text/template/template.go:197 +0x3d0 fp=0xc42004b778 sp=0xc42004b640
github.com/xeipuuv/gojsonschema.formatErrorDescription(0x8efd40, 0x19, 0xc420017da0, 0x0, 0x0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/errors.go:251 +0x533 fp=0xc42004b8a8 sp=0xc42004b778
github.com/xeipuuv/gojsonschema.newError(0x7f3e13b93d58, 0xc420012500, 0xc420011040, 0x74c980, 0xc420016150, 0x7f3e13b937d8, 0xad3f08, 0xc420017da0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/errors.go:232 +0x299 fp=0xc42004b948 sp=0xc42004b8a8
github.com/xeipuuv/gojsonschema.(*Result).addError(0xc420011020, 0x7f3e13b93d58, 0xc420012500, 0xc420011040, 0x74c980, 0xc420016150, 0xc420017da0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/result.go:159 +0x75 fp=0xc42004b9a0 sp=0xc42004b948
github.com/xeipuuv/gojsonschema.(*subSchema).validateObject(0xc42015a000, 0xc42015a000, 0xc420016150, 0xc420011020, 0xc420011040)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:542 +0x1a83 fp=0xc42004bc40 sp=0xc42004b9a0
github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc42015a000, 0xc42015a000, 0x74c980, 0xc420016150, 0xc420011020, 0xc420011040)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:199 +0x1509 fp=0xc42004be10 sp=0xc42004bc40
github.com/xeipuuv/gojsonschema.(*Schema).Validate(0xc420068b80, 0x7f3e13b93bc8, 0xc4200d8ea0, 0x0, 0x0, 0x0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:67 +0x178 fp=0xc42004be90 sp=0xc42004be10
main.validateDocuments.func1(0xc420068b80, 0xc4201488f0, 0x5, 0x5, 0xc420163db0, 0x2, 0x7f3e13b93bc8, 0xc4200d8ea0)
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:125 +0x4a fp=0xc42004bf60 sp=0xc42004be90
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc42004bf68 sp=0xc42004bf60
created by main.validateDocuments
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:138 +0x194

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc420163dbc)
	/usr/lib/golang/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc420163db0)
	/usr/lib/golang/src/sync/waitgroup.go:127 +0xb4
main.validateDocuments(0xc420068b80, 0xc4200a1080, 0x5, 0x8, 0x0, 0x0, 0x0)
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:140 +0x1c1
main.main()
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:65 +0x676

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1

goroutine 19 [runnable]:
main.validateDocuments.func1(0xc420068b80, 0xc4201488f0, 0x5, 0x5, 0xc420163db0, 0x0, 0x7f3e13b93bc8, 0xc4200d8e40)
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:124
created by main.validateDocuments
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:138 +0x194

goroutine 20 [runnable]:
regexp.(*inputString).step(0xc420248e58, 0x16, 0x16, 0x1)
	/usr/lib/golang/src/regexp/regexp.go:286
regexp.(*machine).tryBacktrack(0xc420248d80, 0xc4201a05b0, 0x7f3e13b4f160, 0xc420248e58, 0x1, 0x0, 0xad3930)
	/usr/lib/golang/src/regexp/backtrack.go:214 +0xa3e
regexp.(*machine).backtrack(0xc420248d80, 0x7f3e13b4f160, 0xc420248e58, 0x0, 0x1f, 0x0, 0x15)
	/usr/lib/golang/src/regexp/backtrack.go:336 +0x20a
regexp.(*Regexp).doExecute(0xc4200a2960, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4201a6060, 0x1f, 0x0, 0x0, ...)
	/usr/lib/golang/src/regexp/exec.go:449 +0x423
regexp.(*Regexp).MatchString(0xc4200a2960, 0xc4201a6060, 0x1f, 0x10)
	/usr/lib/golang/src/regexp/regexp.go:411 +0x67
github.com/xeipuuv/gojsonschema.HostnameFormatChecker.IsFormat(0xc4201a6060, 0x1f, 0x74d900)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/format_checkers.go:177 +0x37
github.com/xeipuuv/gojsonschema.(*HostnameFormatChecker).IsFormat(0xad3f08, 0xc4201a6060, 0x1f, 0xc420045288)
	<autogenerated>:403 +0xa1
github.com/xeipuuv/gojsonschema.(*FormatCheckerChain).IsFormat(0xab5bb8, 0xc4201465c8, 0x8, 0x74d900, 0xc42022f820, 0x10)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/format_checkers.go:130 +0x13f
github.com/xeipuuv/gojsonschema.(*subSchema).validateString(0xc4201854a0, 0xc4201854a0, 0x74d900, 0xc42022f810, 0xc4201a6f60, 0xc4201a6f40)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:736 +0x777
github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc4201854a0, 0xc4201854a0, 0x74d900, 0xc42022f7d0, 0xc4201a6f60, 0xc4201a6f40)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:254 +0x228e
github.com/xeipuuv/gojsonschema.(*subSchema).subValidateWithContext(0xc4201854a0, 0x74d900, 0xc42022f7d0, 0xc4201a6f40, 0x0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:75 +0x74
github.com/xeipuuv/gojsonschema.(*subSchema).validateSchema(0xc4201852c0, 0xc4201852c0, 0x74d900, 0xc42022f7d0, 0xc4201a6e00, 0xc4201a6f40)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:306 +0x4dd
github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc42015a000, 0xc4201852c0, 0x74d900, 0xc4201860d0, 0xc4201a6e00, 0xc4201a6f40)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:251 +0x20cc
github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc42015a000, 0xc4201850e0, 0x74d900, 0xc4201860d0, 0xc4201a6e00, 0xc4201a6f40)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:89 +0x83
github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc42015a000, 0xc42015a000, 0x74c980, 0xc4201b2060, 0xc4201a6e00, 0xc4201a6e20)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:206 +0x1714
github.com/xeipuuv/gojsonschema.(*Schema).Validate(0xc420068b80, 0x7f3e13b93bc8, 0xc4200d8e60, 0x0, 0x0, 0x0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:67 +0x178
main.validateDocuments.func1(0xc420068b80, 0xc4201488f0, 0x5, 0x5, 0xc420163db0, 0x1, 0x7f3e13b93bc8, 0xc4200d8e60)
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:125 +0x4a
created by main.validateDocuments
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:138 +0x194

goroutine 22 [runnable]:
main.validateDocuments.func1(0xc420068b80, 0xc4201488f0, 0x5, 0x5, 0xc420163db0, 0x3, 0x7f3e13b93bc8, 0xc4200d8ec0)
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:124
created by main.validateDocuments
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:138 +0x194

goroutine 23 [runnable]:
reflect.ValueOf(0x74d900, 0xc420237610, 0x74d900, 0xc420237610, 0xe0ff5cb4)
	/usr/lib/golang/src/reflect/value.go:2084
github.com/xeipuuv/gojsonschema.isKind(0x74d900, 0xc420237610, 0x18, 0xc4202375f0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/utils.go:42 +0xb6
github.com/xeipuuv/gojsonschema.(*subSchema).validateString(0xc420185680, 0xc420185680, 0x74d900, 0xc420237610, 0xc420171920, 0xc4201718e0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:688 +0x79
github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc420185680, 0xc420185680, 0x74d900, 0xc420237580, 0xc420171920, 0xc4201718e0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:254 +0x228e
github.com/xeipuuv/gojsonschema.(*subSchema).subValidateWithContext(0xc420185680, 0x74d900, 0xc420237580, 0xc4201718e0, 0xc420171900)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:75 +0x74
github.com/xeipuuv/gojsonschema.(*subSchema).validateSchema(0xc4201852c0, 0xc4201852c0, 0x74d900, 0xc420237580, 0xc4201717a0, 0xc4201718e0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:306 +0x4dd
github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc42015a000, 0xc4201852c0, 0x74d900, 0xc420163e90, 0xc4201717a0, 0xc4201718e0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:251 +0x20cc
github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc42015a000, 0xc4201850e0, 0x74d900, 0xc420163e90, 0xc4201717a0, 0xc4201718e0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:89 +0x83
github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc42015a000, 0xc42015a000, 0x74c980, 0xc42015d4a0, 0xc4201717a0, 0xc4201717c0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:206 +0x1714
github.com/xeipuuv/gojsonschema.(*Schema).Validate(0xc420068b80, 0x7f3e13b93bc8, 0xc4200d8ee0, 0x0, 0x0, 0x0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:67 +0x178
main.validateDocuments.func1(0xc420068b80, 0xc4201488f0, 0x5, 0x5, 0xc420163db0, 0x4, 0x7f3e13b93bc8, 0xc4200d8ee0)
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:125 +0x4a
created by main.validateDocuments
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:138 +0x194

goroutine 25 [runnable]:
text/template/parse.lexText(0xc420183180, 0x951fc8)
	/usr/lib/golang/src/text/template/parse/lex.go:262 +0x451
text/template/parse.(*lexer).run(0xc420183180)
	/usr/lib/golang/src/text/template/parse/lex.go:223 +0x52
created by text/template/parse.lex
	/usr/lib/golang/src/text/template/parse/lex.go:216 +0x162

goroutine 35 [runnable]:
text/template/parse.lexText(0xc42019e580, 0x951fc8)
	/usr/lib/golang/src/text/template/parse/lex.go:262 +0x451
text/template/parse.(*lexer).run(0xc42019e580)
	/usr/lib/golang/src/text/template/parse/lex.go:223 +0x52
created by text/template/parse.lex
	/usr/lib/golang/src/text/template/parse/lex.go:216
```

and the second stacktrace:

```
fatal error: concurrent map read and map write

goroutine 6 [running]:
runtime.throw(0x8f2ae0, 0x21)
	/usr/lib/golang/src/runtime/panic.go:547 +0x90 fp=0xc42004d718 sp=0xc42004d700
runtime.mapaccess1_faststr(0x74c280, 0xc42021b230, 0x917160, 0x30, 0x74d900)
	/usr/lib/golang/src/runtime/hashmap_fast.go:202 +0x5b fp=0xc42004d778 sp=0xc42004d718
github.com/xeipuuv/gojsonschema.formatErrorDescription(0x917160, 0x30, 0xc4201a5fb0, 0x0, 0x0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/errors.go:248 +0x83f fp=0xc42004d8a8 sp=0xc42004d778
github.com/xeipuuv/gojsonschema.newError(0x7fb60f6d9dd0, 0xc4201a2640, 0xc420190e20, 0x74c980, 0xc4201a4060, 0x7fb60f6d9720, 0xad3f08, 0xc4201a5fb0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/errors.go:232 +0x299 fp=0xc42004d948 sp=0xc42004d8a8
github.com/xeipuuv/gojsonschema.(*Result).addError(0xc420190e00, 0x7fb60f6d9dd0, 0xc4201a2640, 0xc420190e20, 0x74c980, 0xc4201a4060, 0xc4201a5fb0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/result.go:159 +0x75 fp=0xc42004d9a0 sp=0xc42004d948
github.com/xeipuuv/gojsonschema.(*subSchema).validateObject(0xc42014c000, 0xc42014c000, 0xc4201a4060, 0xc420190e00, 0xc420190e20)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:584 +0xc10 fp=0xc42004dc40 sp=0xc42004d9a0
github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc42014c000, 0xc42014c000, 0x74c980, 0xc4201a4060, 0xc420190e00, 0xc420190e20)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:199 +0x1509 fp=0xc42004de10 sp=0xc42004dc40
github.com/xeipuuv/gojsonschema.(*Schema).Validate(0xc420012d00, 0x7fb60f6d9b10, 0xc4200cd080, 0x0, 0x0, 0x0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:67 +0x178 fp=0xc42004de90 sp=0xc42004de10
main.validateDocuments.func1(0xc420012d00, 0xc42013cb60, 0x5, 0x5, 0xc420155f10, 0x1, 0x7fb60f6d9b10, 0xc4200cd080)
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:125 +0x4a fp=0xc42004df60 sp=0xc42004de90
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc42004df68 sp=0xc42004df60
created by main.validateDocuments
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:138 +0x194

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc420155f1c)
	/usr/lib/golang/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc420155f10)
	/usr/lib/golang/src/sync/waitgroup.go:127 +0xb4
main.validateDocuments(0xc420012d00, 0xc420097080, 0x5, 0x8, 0x0, 0x0, 0x0)
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:140 +0x1c1
main.main()
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:65 +0x676

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [runnable]:
main.validateDocuments.func1(0xc420012d00, 0xc42013cb60, 0x5, 0x5, 0xc420155f10, 0x0, 0x7fb60f6d9b10, 0xc4200cd060)
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:124
created by main.validateDocuments
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:138 +0x194

goroutine 7 [runnable]:
github.com/xeipuuv/gojsonschema.(*subSchema).validateObject(0xc42014c000, 0xc42014c000, 0xc4201cc060, 0xc4201c2e00, 0xc4201c2e20)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:563 +0x77f
github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc42014c000, 0xc42014c000, 0x74c980, 0xc4201cc060, 0xc4201c2e00, 0xc4201c2e20)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:199 +0x1509
github.com/xeipuuv/gojsonschema.(*Schema).Validate(0xc420012d00, 0x7fb60f6d9b10, 0xc4200cd0c0, 0x0, 0x0, 0x0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:67 +0x178
main.validateDocuments.func1(0xc420012d00, 0xc42013cb60, 0x5, 0x5, 0xc420155f10, 0x2, 0x7fb60f6d9b10, 0xc4200cd0c0)
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:125 +0x4a
created by main.validateDocuments
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:138 +0x194

goroutine 8 [runnable]:
main.validateDocuments.func1(0xc420012d00, 0xc42013cb60, 0x5, 0x5, 0xc420155f10, 0x3, 0x7fb60f6d9b10, 0xc4200cd0e0)
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:124
created by main.validateDocuments
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:138 +0x194

goroutine 9 [runnable]:
github.com/xeipuuv/gojsonschema.(*subSchema).validateString(0xc420177680, 0xc420177680, 0x74d900, 0xc42022d870, 0xc42015fc60, 0xc42015fae0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:736 +0x723
github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc420177680, 0xc420177680, 0x74d900, 0xc42022d640, 0xc42015fc60, 0xc42015fae0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:254 +0x228e
github.com/xeipuuv/gojsonschema.(*subSchema).subValidateWithContext(0xc420177680, 0x74d900, 0xc42022d640, 0xc42015fae0, 0xc42015fbe0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:75 +0x74
github.com/xeipuuv/gojsonschema.(*subSchema).validateSchema(0xc420176f00, 0xc420176f00, 0x74d900, 0xc42022d640, 0xc42015f9e0, 0xc42015fae0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:306 +0x4dd
github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc42014c000, 0xc420176f00, 0x74d900, 0xc420155fe0, 0xc42015f9e0, 0xc42015fae0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:251 +0x20cc
github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc42014c000, 0xc420176d20, 0x74d900, 0xc420155fe0, 0xc42015f9e0, 0xc42015fae0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:89 +0x83
github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc42014c000, 0xc42014c000, 0x74c980, 0xc42014f590, 0xc42015f9e0, 0xc42015fa00)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:206 +0x1714
github.com/xeipuuv/gojsonschema.(*Schema).Validate(0xc420012d00, 0x7fb60f6d9b10, 0xc4200cd100, 0x0, 0x0, 0x0)
	/home/johan/go/src/github.com/xeipuuv/gojsonschema/validation.go:67 +0x178
main.validateDocuments.func1(0xc420012d00, 0xc42013cb60, 0x5, 0x5, 0xc420155f10, 0x4, 0x7fb60f6d9b10, 0xc4200cd100)
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:125 +0x4a
created by main.validateDocuments
	/home/johan/go/src/github.com/johandorland/gojsonvalidator/gojsonvalidator.go:138 +0x194

goroutine 11 [runnable]:
text/template/parse.lexText(0xc420173180, 0x951fc8)
	/usr/lib/golang/src/text/template/parse/lex.go:262 +0x451
text/template/parse.(*lexer).run(0xc420173180)
	/usr/lib/golang/src/text/template/parse/lex.go:223 +0x52
created by text/template/parse.lex
	/usr/lib/golang/src/text/template/parse/lex.go:216 +0x162

goroutine 12 [runnable]:
text/template/parse.lexText(0xc420173280, 0x951fc8)
	/usr/lib/golang/src/text/template/parse/lex.go:262 +0x451
text/template/parse.(*lexer).run(0xc420173280)
	/usr/lib/golang/src/text/template/parse/lex.go:223 +0x52
created by text/template/parse.lex
	/usr/lib/golang/src/text/template/parse/lex.go:216 +0x162
```

**Comment by xeipuuv** [comment]
thanks :)

**Comment by arushigarg** [comment]
Hey,
Is this fixed now. I am using this library and getting this error : 
```
fatal error: concurrent map read and map write

goroutine 1113 [running]:
runtime.throw(0x39fa571, 0x21)
        /root/.uber-go-versions/gimme/versions/go1.12.4.linux.amd64/src/runtime/panic.go:617 +0x72 fp=0xc07498e7e0 sp=0xc07498e7b0 pc=0x43b8c2
runtime.mapaccess2_faststr(0x33b5140, 0xc000683a10, 0xc074b7c5b6, 0xa, 0x1, 0x419b01)
        /root/.uber-go-versions/gimme/versions/go1.12.4.linux.amd64/src/runtime/map_faststr.go:116 +0x4a9 fp=0xc07498e850 sp=0xc07498e7e0 pc=0x420bb9
code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema.(*FormatCheckerChain).IsFormat(...)
        code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema/format_checkers.go:156
code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema.(*subSchema).validateString(0xc074c74400, 0xc074c74400, 0x3276a00, 0xc074d88f20, 0xc074d73080, 0xc074d73040)
        code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema/validation.go:804 +0x19c fp=0xc07498e988 sp=0xc07498e850 pc=0x20bb8cc
code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc074c74400, 0xc074c74400, 0x3276a00, 0xc074d88e60, 0xc074d73080, 0xc074d73040)
        code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema/validation.go:243 +0x1552 fp=0xc07498eae8 sp=0xc07498e988 pc=0x20b4d92
code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema.(*subSchema).subValidateWithContext(0xc074c74400, 0x3276a00, 0xc074d88e60, 0xc074d73040, 0xc074d73060)
        code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema/validation.go:64 +0x6d fp=0xc07498eb30 sp=0xc07498eae8 pc=0x20b381d
code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema.(*subSchema).validateSchema(0xc074c74000, 0xc074c74000, 0x3276a00, 0xc074d88e60, 0xc074d73000, 0xc074d73040)
        code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema/validation.go:295 +0x1ef fp=0xc07498ed48 sp=0xc07498eb30 pc=0x20b592f
code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc074c71c00, 0xc074c74000, 0x3276a00, 0xc074c8ab30, 0xc074d73000, 0xc074d73040)
        code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema/validation.go:240 +0x1417 fp=0xc07498eea8 sp=0xc07498ed48 pc=0x20b4c57
code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc074c71c00, 0xc074c71c00, 0x33b6160, 0xc074d121e0, 0xc074d73000, 0xc074d72fc0)
        code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema/validation.go:195 +0x72b fp=0xc07498f008 sp=0xc07498eea8 pc=0x20b3f6b
code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema.(*subSchema).subValidateWithContext(0xc074c71c00, 0x33b6160, 0xc074d121e0, 0xc074d72fc0, 0xc074d72fe0)
        code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema/validation.go:64 +0x6d fp=0xc07498f050 sp=0xc07498f008 pc=0x20b381d
code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema.(*subSchema).validateSchema(0xc074c71800, 0xc074c71800, 0x33b6160, 0xc074d121e0, 0xc074b69180, 0xc074d72fc0)
        code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema/validation.go:295 +0x1ef fp=0xc07498f268 sp=0xc07498f050 pc=0x20b592f
code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc074a1bc00, 0xc074c71800, 0x33b6160, 0xc074d121e0, 0xc074b69180, 0xc074d72fc0)
        code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema/validation.go:186 +0x546 fp=0xc07498f3c8 sp=0xc07498f268 pc=0x20b3d86
code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc074a1bc00, 0xc074c02800, 0x33b6160, 0xc074d12150, 0xc074b69180, 0xc074d72c00)
        code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema/validation.go:195 +0x72b fp=0xc07498f528 sp=0xc07498f3c8 pc=0x20b3f6b
code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema.(*subSchema).validateRecursive(0xc074a1bc00, 0xc074a1bc00, 0x33b6160, 0xc074b67ec0, 0xc074b69180, 0xc074b691a0)
        code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema/validation.go:195 +0x72b fp=0xc07498f688 sp=0xc07498f528 pc=0x20b3f6b
code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema.(*Schema).validateDocument(0xc0748e9640, 0x33b6160, 0xc074b67ec0, 0x0)
        code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema/validation.go:58 +0xae fp=0xc07498f6d0 sp=0xc07498f688 pc=0x20b375e
code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema.(*Schema).Validate(0xc0748e9640, 0x42ebde0, 0xc074aa3410, 0x0, 0x0, 0xc074aa3410)
        code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema/validation.go:52 +0x6b fp=0xc07498f708 sp=0xc07498f6d0 pc=0x20b367b
code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema.Validate(0x42ebe20, 0xc000b272e0, 0x42ebde0, 0xc074aa3410, 0x6ec0ff0, 0x6e956e0, 0x0)
        code.uber.internal/finance/banker/vendor/github.com/xeipuuv/gojsonschema/validation.go:44 +0x87 fp=0xc07498f748 sp=0xc07498f708 pc=0x20b35d7
code.uber.internal/finance/banker/models/jsonschemavalidator.(*schemaValidator).ValidateTxn(0xc000bacdb0, 0xc07454ebe0, 0x0, 0x0)
```

**Comment by johandorland** [comment]
@arushigarg 

The concurrent map write as reported in this issue has been fixed, it looks like you found another instance of where a concurrent map write occurs. It looks like you are adding a new format whilst also performing validation. That is somewhat iffy as you'd rather not be dependent on the order of execution when validating a schema, it should in no way cause a panic.

 I just merged a fix on master, but I'm curious how you managed to get to this race condition 😆

**Comment by arushigarg** [comment]
Hi @johandorland 
Yeah so what I have done is, I am initialising the schemaLoader variable in the starting I have added some custom formatters of my own, using `gojsonschema.FormatCheckers.Add`.
Meanwhile I am passing the

**Comment by arushigarg** [comment]
Hi @johandorland 
So what I was doing was initialising the schemaLoader variable at the starting of my app, thus creating a singleton instance for all the jsons. Whereas I was adding my custom validation later with every new instance. I added all the custom validations at initialisation time. Hence the issue was resolved.
Thanks for helping :) .
