### ISSUE TITLE
gojsonschema.Compile() is not thread safe

### ISSUE THREAD

**Issue by vitali108** [xeipuuv/gojsonschema#292]
When invoking `gojsonschema.Compile()` from multiple threads I got the following panic:
```
fatal error: concurrent map read and map write
goroutine 10 [running]:
runtime.throw(0x15c439a, 0x21)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc00042a788 sp=0xc00042a758 pc=0x102f262
runtime.mapaccess2_faststr(0x1518620, 0xc000298780, 0xc000cbc280, 0x53, 0x0, 0x104475e)
	/usr/local/go/src/runtime/map_faststr.go:116 +0x48f fp=0xc00042a7f8 sp=0xc00042a788 pc=0x101479f
github.com/xeipuuv/gojsonschema.(*schemaPool).GetDocument(0xc000268840, 0xc001e1a380, 0xc001505dd0, 0x3, 0x3, 0x101000100, 0xc0007b3039, 0xc0007b3007, 0x15b47a5)
	/Users/vitali/go/pkg/mod/github.com/xeipuuv/gojsonschema@v1.2.0/schemaPool.go:158 +0xfc fp=0xc00042a9d8 sp=0xc00042a7f8 pc=0x13f8c0c
github.com/xeipuuv/gojsonschema.(*Schema).parseReference(0xc001bda740, 0x1519340, 0xc0002e8630, 0xc001fa0000, 0x1a02d80, 0x12f4300)
	/Users/vitali/go/pkg/mod/github.com/xeipuuv/gojsonschema@v1.2.0/schema.go:979 +0x167 fp=0xc00042aac0 sp=0xc00042a9d8 pc=0x13f5827
github.com/xeipuuv/gojsonschema.(*Schema).parseSchema(0xc001bda740, 0x1519340, 0xc0002e8630, 0xc001fa0000, 0x0, 0x0)
	/Users/vitali/go/pkg/mod/github.com/xeipuuv/gojsonschema@v1.2.0/schema.go:239 +0xb30f fp=0xc00042b260 sp=0xc00042aac0 pc=0x13f457f
github.com/xeipuuv/gojsonschema.(*Schema).parse(...)
	/Users/vitali/go/pkg/mod/github.com/xeipuuv/gojsonschema@v1.2.0/schema.go:63
github.com/xeipuuv/gojsonschema.(*SchemaLoader).Compile(0xc000268820, 0x1687220, 0xc001128d00, 0x8, 0x8, 0xc000095100)
	/Users/vitali/go/pkg/mod/github.com/xeipuuv/gojsonschema@v1.2.0/schemaLoader.go:200 +0x2d2 fp=0xc00042b358 sp=0xc00042b260 pc=0x13f78b2
```

**Comment by willson-chen** [comment]
@vitali108 Could you please provide a test case?
